macro_ss = """
-DMBED_MINIMAL_PRINTF -DMBED_TRAP_ERRORS_ENABLED=1 
-DARDUINO=10607 -DARDUINO_APOLLO3_SFE_ARTEMIS_NANO -DARDUINO_ARCH_MBED 
-DARDUINO_ARCH_APOLLO3 -DMBED_NO_GLOBAL_USING_DIRECTIVE -DCORDIO_ZERO_COPY_HCI 
-DAM_CUSTOM_BDADDR -DAM_PACKAGE_BGA -DARDUINO_BLE_FIX -DARM_MATH_CM4 
-DCOMPONENT_FLASHIAP=1 -DCORDIO_ZERO_COPY_HCI -DDEVICE_FLASH=1 -DDEVICE_I2C=1 
-DDEVICE_INTERRUPTIN=1 -DDEVICE_LPTICKER=1 -DDEVICE_MPU=1 -DDEVICE_SERIAL=1 
-DDEVICE_SPI=1 -DDEVICE_STDIO_MESSAGES=1 -DDEVICE_USTICKER=1 -DFEATURE_BLE=1 
-DTARGET_AMA3B1KK -DTARGET_Ambiq_Micro -DTARGET_Apollo3 -DTARGET_CORDIO 
-DTARGET_CORTEX -DTARGET_CORTEX_M -DTARGET_FAMILY_Apollo3 -DTARGET_LIKE_CORTEX_M4 
-DTARGET_LIKE_MBED -DTARGET_M4 -DTARGET_NAME=SFE_ARTEMIS_NANO -DTARGET_RELEASE 
-DTARGET_RTOS_M4_M7 -DTARGET_SFE_ARTEMIS_NANO -DTOOLCHAIN_GCC -DTOOLCHAIN_GCC_ARM 
-D__CMSIS_RTOS -D__CORTEX_M4 -D__FPU_PRESENT=1 -D__MBED_CMSIS_RTOS_CM -D__MBED__=1
"""

macros = macro_ss.split()

def process_macro():
    for macro in macros:
        assert macro.startswith('-D'), "macro should start with -D"
        macro = macro.replace('-D', '')
        print(f'"{macro}",')


include_ss = """
-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/arduino 
-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/variants/SFE_ARTEMIS_NANO 
-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/libraries/Wire/src 
-I/Users/yangd19/Documents/Arduino/libraries/VL53L1X 
-I/Users/yangd19/Documents/Arduino/libraries/ArduinoBLE/src 
-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/arduino 
-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/arduino/mbed-bridge 
-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/arduino/mbed-bridge/core-api 
-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/arduino/mbed-bridge/core-api/api/deprecated 
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/cmsis"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/cmsis/TARGET_CORTEX_M"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/802.15.4_RF"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/802.15.4_RF/atmel-rf-driver"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/802.15.4_RF/atmel-rf-driver/atmel-rf-driver"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/802.15.4_RF/atmel-rf-driver/source"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/802.15.4_RF/mcr20a-rf-driver"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/802.15.4_RF/mcr20a-rf-driver/mcr20a-rf-driver"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/802.15.4_RF/mcr20a-rf-driver/source"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver/source"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver/stm-s2lp-rf-driver"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/storage/blockdevice/COMPONENT_FLASHIAP"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/storage/blockdevice/COMPONENT_FLASHIAP/COMMON"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/wifi"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/wifi/esp8266-driver"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/wifi/esp8266-driver/ESP8266"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/drivers/internal"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/events"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/events/internal"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/ble"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/ble/common"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/ble/gap"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/ble/generic"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/ble/pal"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/ble/services"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/source"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/source/gap"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/source/generic"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_Ambiq_Micro"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_Ambiq_Micro/TARGET_Apollo3"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_Ambiq_Micro/hal"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_Ambiq_Micro/hal/apollo3"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/driver"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/source"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/include"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/hci"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/hci/dual_chip"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/sec"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/sec/common"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/att"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/cfg"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/dm"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/hci"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/l2c"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/smp"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/platform"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/platform/include"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/wsf"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/wsf/include"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/wsf/include/util"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/wsf/sources"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/wsf/sources/port"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/wsf/sources/port/baremetal"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack_adaptation"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/API"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/AT"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/common"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/device"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/Altair"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/Altair/ALT1250"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/Altair/ALT1250/PPP"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/GEMALTO"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/GEMALTO/CINTERION"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/GENERIC"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/GENERIC/GENERIC_AT3GPP"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/MultiTech"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/MultiTech/DragonflyNano"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/MultiTech/DragonflyNano/PPP"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/QUECTEL"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/QUECTEL/BC95"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/QUECTEL/BG96"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/QUECTEL/EC2X"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/QUECTEL/M26"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/QUECTEL/UG96"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/RiotMicro"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/RiotMicro/AT"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/TELIT"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/TELIT/HE910"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/TELIT/ME310"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/TELIT/ME910"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/UBLOX"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/UBLOX/AT"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/UBLOX/N2XX"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/UBLOX/PPP"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/device_key"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/device_key/source"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/greentea-client"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/greentea-client/greentea-client"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/mbed-client-cli"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/mbed-client-cli/mbed-client-cli"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/mbed-client-randlib"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/mbed-client-randlib/mbed-client-randlib"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/mbed-client-randlib/mbed-client-randlib/platform"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/mbed-coap"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/mbed-coap/mbed-coap"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/mbed-coap/source"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/mbed-coap/source/include"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/mbed-trace"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/mbed-trace/mbed-trace"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/nanostack-libservice"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/nanostack-libservice/mbed-client-libservice"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/nanostack-libservice/mbed-client-libservice/platform"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/unity"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/unity/unity"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/utest"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/utest/utest"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lorawan"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lorawan/lorastack"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lorawan/lorastack/mac"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lorawan/lorastack/phy"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lorawan/system"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip-sys"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip-sys/arch"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip/src"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip/src/include"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip/src/include/compat"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip/src/include/compat/posix"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip/src/include/compat/posix/arpa"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip/src/include/compat/posix/net"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip/src/include/compat/posix/sys"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip/src/include/lwip"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip/src/include/lwip/priv"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip/src/include/lwip/prot"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip/src/include/netif"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/mbedtls"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/mbedtls/inc"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/mbedtls/inc/mbedtls"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/mbedtls/platform"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/mbedtls/platform/inc"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/coap-service"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/coap-service/coap-service"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/coap-service/source"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/coap-service/source/include"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/mbed-mesh-api"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/mbed-mesh-api/mbed-mesh-api"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/mbed-mesh-api/source"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/mbed-mesh-api/source/include"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/nanostack-hal-mbed-cmsis-rtos"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/nanostack-interface"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack-eventloop"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack-eventloop/nanostack-event-loop"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack-eventloop/nanostack-event-loop/platform"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack-eventloop/source"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/nanostack"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/nanostack/platform"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/Bootstraps"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/Fragmentation"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/IPHC_Decode"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/MAC"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/Mesh"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/ND"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/NVM"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/Thread"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/BorderRouter"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Common_Protocols"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Core"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Core/include"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/DHCPv6_Server"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/DHCPv6_client"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/MAC"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/MAC/virtual_rf"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/MLE"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/MPL"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/NWK_INTERFACE"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/NWK_INTERFACE/Include"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/RPL"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security/Common"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security/PANA"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security/TLS"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security/eapol"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security/kmp"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols/fwh_sec_prot"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols/gkh_sec_prot"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols/key_sec_prot"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols/tls_sec_prot"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/Neighbor_cache"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/Trickle"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/blacklist"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/etx"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/fhss"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/fnv_hash"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/hmac"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/ieee_802_11"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/load_balance"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mac_neighbor_table"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/port"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/port/compiler"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/port/cpu"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services/dns"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services/mdns"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services/poll"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services/serial"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/stack"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mle_service"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/nd_proxy"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/nist_aes_kw"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/pan_blacklist"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/utils"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/whiteboard"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/configs"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/configs/base"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/ipv6_stack"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/libDHCPv6"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/libNET"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/libNET/src"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/netsocket"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/netsocket/ppp"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/netsocket/ppp/include"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/netsocket/ppp/include/polarssl"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/acore"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/acore/acore"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/controllers"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/nfc"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/nfc/ndef"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/nfc/ndef/common"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/stack"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/stack/ndef"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/stack/platform"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/stack/tech"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/stack/tech/iso7816"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/stack/tech/isodep"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/stack/tech/type4"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/stack/transceiver"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/stack/transceiver/pn512"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/blockdevice"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/filesystem"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/filesystem/fat"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/filesystem/fat/ChaN"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/filesystem/littlefs"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/filesystem/littlefs/littlefs"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/filesystem/littlefsv2"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/filesystem/littlefsv2/littlefs"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/kvstore"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/kvstore/conf"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/kvstore/direct_access_devicekey"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/kvstore/filesystemstore"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/kvstore/global_api"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/kvstore/include"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/kvstore/kv_map"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/kvstore/securestore"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/kvstore/tdbstore"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/hal"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/hal/usb"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/platform"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/platform/cxxsupport"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/platform/internal"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/platform/source"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/platform/source/minimal-printf"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/rtos"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/rtos/source"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/rtos/source/TARGET_CORTEX"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/rtos/source/TARGET_CORTEX/rtx4"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/rtos/source/TARGET_CORTEX/rtx5"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/rtos/source/TARGET_CORTEX/rtx5/Include"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Config"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Include"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Source"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3/TARGET_SFE_ARTEMIS_NANO"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3/TARGET_SFE_ARTEMIS_NANO/bsp"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3/device"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3/sdk"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3/sdk/CMSIS"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3/sdk/CMSIS/AmbiqMicro"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3/sdk/CMSIS/AmbiqMicro/Include"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3/sdk/mcu"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3/sdk/mcu/apollo3"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3/sdk/mcu/apollo3/hal"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3/sdk/mcu/apollo3/regs"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/sdk"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/sdk/devices"
"-I/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/sdk/utils"

"""

def process_include():
    include_ss_formed = include_ss.replace('"', '')
    includes = include_ss_formed.split()
    for include in includes:
        assert include.startswith('-I'), "Include option should start with -I"
        include = include.replace('-I', '')
        print(f'"{include}",')

if __name__ == "__main__":
    process_include()




"""
Output:

"MBED_MINIMAL_PRINTF",
"MBED_TRAP_ERRORS_ENABLED=1",
"ARDUINO=10607",
"ARDUINO_APOLLO3_SFE_ARTEMIS_NANO",
"ARDUINO_ARCH_MBED",
"ARDUINO_ARCH_APOLLO3",
"MBED_NO_GLOBAL_USING_DIRECTIVE",
"CORDIO_ZERO_COPY_HCI",
"AM_CUSTOM_BDADDR",
"AM_PACKAGE_BGA",
"ARDUINO_BLE_FIX",
"ARM_MATH_CM4",
"COMPONENT_FLASHIAP=1",
"CORDIO_ZERO_COPY_HCI",
"DEVICE_FLASH=1",
"DEVICE_I2C=1",
"DEVICE_INTERRUPTIN=1",
"DEVICE_LPTICKER=1",
"DEVICE_MPU=1",
"DEVICE_SERIAL=1",
"DEVICE_SPI=1",
"DEVICE_STDIO_MESSAGES=1",
"DEVICE_USTICKER=1",
"FEATURE_BLE=1",
"TARGET_AMA3B1KK",
"TARGET_Ambiq_Micro",
"TARGET_Apollo3",
"TARGET_CORDIO",
"TARGET_CORTEX",
"TARGET_CORTEX_M",
"TARGET_FAMILY_Apollo3",
"TARGET_LIKE_CORTEX_M4",
"TARGET_LIKE_MBED",
"TARGET_M4",
"TARGET_NAME=SFE_ARTEMIS_NANO",
"TARGET_RELEASE",
"TARGET_RTOS_M4_M7",
"TARGET_SFE_ARTEMIS_NANO",
"TOOLCHAIN_GCC",
"TOOLCHAIN_GCC_ARM",
"__CMSIS_RTOS",
"__CORTEX_M4",
"__FPU_PRESENT=1",
"__MBED_CMSIS_RTOS_CM",
"__MBED__=1",

"""

"""
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/arduino",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/variants/SFE_ARTEMIS_NANO",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/libraries/Wire/src",
"/Users/yangd19/Documents/Arduino/libraries/VL53L1X",
"/Users/yangd19/Documents/Arduino/libraries/ArduinoBLE/src",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/arduino",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/arduino/mbed-bridge",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/arduino/mbed-bridge/core-api",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/arduino/mbed-bridge/core-api/api/deprecated",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/cmsis",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/cmsis/TARGET_CORTEX_M",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/802.15.4_RF",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/802.15.4_RF/atmel-rf-driver",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/802.15.4_RF/atmel-rf-driver/atmel-rf-driver",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/802.15.4_RF/atmel-rf-driver/source",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/802.15.4_RF/mcr20a-rf-driver",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/802.15.4_RF/mcr20a-rf-driver/mcr20a-rf-driver",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/802.15.4_RF/mcr20a-rf-driver/source",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver/source",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver/stm-s2lp-rf-driver",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/storage/blockdevice/COMPONENT_FLASHIAP",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/storage/blockdevice/COMPONENT_FLASHIAP/COMMON",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/wifi",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/wifi/esp8266-driver",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/components/wifi/esp8266-driver/ESP8266",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/drivers/internal",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/events",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/events/internal",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/ble",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/ble/common",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/ble/gap",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/ble/generic",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/ble/pal",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/ble/services",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/source",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/source/gap",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/source/generic",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_Ambiq_Micro",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_Ambiq_Micro/TARGET_Apollo3",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_Ambiq_Micro/hal",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_Ambiq_Micro/hal/apollo3",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/driver",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/source",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/include",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/hci",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/hci/dual_chip",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/sec",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/sec/common",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/att",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/cfg",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/dm",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/hci",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/l2c",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/smp",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/platform",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/platform/include",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/wsf",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/wsf/include",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/wsf/include/util",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/wsf/sources",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/wsf/sources/port",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack/wsf/sources/port/baremetal",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/stack_adaptation",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/API",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/AT",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/common",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/device",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/Altair",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/Altair/ALT1250",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/Altair/ALT1250/PPP",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/GEMALTO",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/GEMALTO/CINTERION",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/GENERIC",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/GENERIC/GENERIC_AT3GPP",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/MultiTech",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/MultiTech/DragonflyNano",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/MultiTech/DragonflyNano/PPP",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/QUECTEL",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/QUECTEL/BC95",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/QUECTEL/BG96",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/QUECTEL/EC2X",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/QUECTEL/M26",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/QUECTEL/UG96",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/RiotMicro",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/RiotMicro/AT",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/TELIT",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/TELIT/HE910",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/TELIT/ME310",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/TELIT/ME910",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/UBLOX",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/UBLOX/AT",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/UBLOX/N2XX",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/cellular/framework/targets/UBLOX/PPP",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/device_key",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/device_key/source",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/greentea-client",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/greentea-client/greentea-client",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/mbed-client-cli",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/mbed-client-cli/mbed-client-cli",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/mbed-client-randlib",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/mbed-client-randlib/mbed-client-randlib",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/mbed-client-randlib/mbed-client-randlib/platform",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/mbed-coap",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/mbed-coap/mbed-coap",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/mbed-coap/source",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/mbed-coap/source/include",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/mbed-trace",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/mbed-trace/mbed-trace",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/nanostack-libservice",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/nanostack-libservice/mbed-client-libservice",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/nanostack-libservice/mbed-client-libservice/platform",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/unity",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/unity/unity",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/utest",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/frameworks/utest/utest",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lorawan",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lorawan/lorastack",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lorawan/lorastack/mac",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lorawan/lorastack/phy",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lorawan/system",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip-sys",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip-sys/arch",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip/src",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip/src/include",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip/src/include/compat",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip/src/include/compat/posix",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip/src/include/compat/posix/arpa",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip/src/include/compat/posix/net",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip/src/include/compat/posix/sys",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip/src/include/lwip",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip/src/include/lwip/priv",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip/src/include/lwip/prot",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/lwipstack/lwip/src/include/netif",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/mbedtls",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/mbedtls/inc",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/mbedtls/inc/mbedtls",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/mbedtls/platform",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/mbedtls/platform/inc",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/coap-service",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/coap-service/coap-service",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/coap-service/source",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/coap-service/source/include",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/mbed-mesh-api",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/mbed-mesh-api/mbed-mesh-api",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/mbed-mesh-api/source",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/mbed-mesh-api/source/include",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/nanostack-hal-mbed-cmsis-rtos",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/nanostack-interface",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack-eventloop",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack-eventloop/nanostack-event-loop",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack-eventloop/nanostack-event-loop/platform",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack-eventloop/source",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/nanostack",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/nanostack/platform",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/Bootstraps",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/Fragmentation",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/IPHC_Decode",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/MAC",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/Mesh",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/ND",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/NVM",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/Thread",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/BorderRouter",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Common_Protocols",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Core",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Core/include",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/DHCPv6_Server",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/DHCPv6_client",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/MAC",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/MAC/virtual_rf",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/MLE",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/MPL",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/NWK_INTERFACE",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/NWK_INTERFACE/Include",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/RPL",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security/Common",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security/PANA",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security/TLS",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security/eapol",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security/kmp",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols/fwh_sec_prot",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols/gkh_sec_prot",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols/key_sec_prot",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols/tls_sec_prot",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/Neighbor_cache",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/Trickle",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/blacklist",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/etx",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/fhss",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/fnv_hash",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/hmac",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/ieee_802_11",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/load_balance",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mac_neighbor_table",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/port",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/port/compiler",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/port/cpu",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services/dns",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services/mdns",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services/poll",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services/serial",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/stack",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mle_service",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/nd_proxy",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/nist_aes_kw",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/pan_blacklist",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/utils",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/whiteboard",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/configs",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/configs/base",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/ipv6_stack",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/libDHCPv6",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/libNET",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nanostack/sal-stack-nanostack/source/libNET/src",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/netsocket",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/netsocket/ppp",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/netsocket/ppp/include",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/netsocket/ppp/include/polarssl",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/acore",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/acore/acore",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/controllers",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/nfc",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/nfc/ndef",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/nfc/ndef/common",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/stack",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/stack/ndef",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/stack/platform",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/stack/tech",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/stack/tech/iso7816",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/stack/tech/isodep",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/stack/tech/type4",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/stack/transceiver",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/nfc/stack/transceiver/pn512",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/blockdevice",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/filesystem",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/filesystem/fat",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/filesystem/fat/ChaN",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/filesystem/littlefs",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/filesystem/littlefs/littlefs",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/filesystem/littlefsv2",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/filesystem/littlefsv2/littlefs",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/kvstore",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/kvstore/conf",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/kvstore/direct_access_devicekey",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/kvstore/filesystemstore",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/kvstore/global_api",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/kvstore/include",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/kvstore/kv_map",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/kvstore/securestore",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/features/storage/kvstore/tdbstore",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/hal",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/hal/usb",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/platform",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/platform/cxxsupport",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/platform/internal",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/platform/source",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/platform/source/minimal-printf",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/rtos",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/rtos/source",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/rtos/source/TARGET_CORTEX",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/rtos/source/TARGET_CORTEX/rtx4",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/rtos/source/TARGET_CORTEX/rtx5",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/rtos/source/TARGET_CORTEX/rtx5/Include",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Config",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Include",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Source",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3/TARGET_SFE_ARTEMIS_NANO",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3/TARGET_SFE_ARTEMIS_NANO/bsp",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3/device",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3/sdk",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3/sdk/CMSIS",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3/sdk/CMSIS/AmbiqMicro",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3/sdk/CMSIS/AmbiqMicro/Include",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3/sdk/mcu",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3/sdk/mcu/apollo3",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3/sdk/mcu/apollo3/hal",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/TARGET_Apollo3/sdk/mcu/apollo3/regs",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/sdk",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/sdk/devices",
"/Users/yangd19/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.2.1/cores/mbed-os/targets/TARGET_Ambiq_Micro/sdk/utils",
"""